// Commmon
export const VIDEO_CALL = "VIDEO_CALL"
export const VIDEO_ROOM = "VIDEO_ROOM"
export const SCREEN_SHARE = "SCREEN_SHARE"
export const SUCCESS_ATTACH_JANUS = "SUCCESS_ATTACH_JANUS"

// VideoCall
export const EVENT_REGISTERED = "EVENT_REGISTERED"
export const EVENT_CALLING = "EVENT_CALLING"
export const EVENT_INCOMINGCALL = "EVENT_INCOMINGCALL"
export const EVENT_ACCEPTED = "EVENT_ACCEPTED"
export const EVENT_UPDATE = "EVENT_UPDATE"
export const EVENT_HANGUP = "EVENT_HANGUP"
export const EVENT_SIMULCAST = "EVENT_SIMULCAST"
